[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[profile.ci]
fuzz = { runs = 100 }
invariant = { runs = 10 }
via_ir = true

